### ISSUE TITLE
Jenkins build error when using with AppCompatibility v7:21.0.2

### ISSUE THREAD

**Issue by pvub** [freshdesk/mobihelp-android#10]
Can't pull the dependencies when using v7 Application Compatibility libraries (21.0.2). These libraries are not available in maven central.

**Comment by tryprasannan** [comment]
We can't make appcompat-v7 available in maven central, as its Google's prerogative. You can use either [maven-android-sdk-deployer] or Android SDK Manager to download the Android Support Repository & Google Repository and deploy the libraries to your local repository to use them.

[maven-android-sdk-deployer]: https://github.com/mosabua/maven-android-sdk-deployer

**Comment by pvub** [comment]
@tryprasannan Since appcompat-v7 is not available in maven central, is it possible to add the dependency locally in this repo itself? I am asking this, because we need the ability to run the build on a third-party jenkins host, and we wont be able to create a local maven repo on that host. By adding the dependency locally we don't have to download this, and thus reduces the chance of build failure.

**Comment by tryprasannan** [comment]
@pvub Google's licensing terms forbids us from redistributing. You can make a copy of appcompat available in your server and let the build process fetch from there or fork this repo and add appcomapt-v7 for your use alone.
