### ISSUE TITLE
Application Not Responding

### ISSUE THREAD

**Issue by mlucchini** [freshdesk/mobihelp-android#14]
The device hangs immediately if I call Mobihelp.showSupport or if I select an entry in the view shown after I call Mobihelp.showConversations. Mobihelp.sendFeedback is fine however.

Hanging seems to happen in SolutionArticleListActivity. Can I get the SDK source code?

Using Mobihelp SDK 1.3.1.

**Comment by mlucchini** [comment]
Getting crashes as well.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wanderer.pulse/com.freshdesk.mobihelp.activity.ConversationActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class <unknown>

**Comment by hrishikesh-p** [comment]
Hi .. 

this looks like a manifest merger issue usually fixed by a clean build. If it is still not resolved,  Can you please let us know the Android SDK target  version ? 

If you are using AppCompat , can you also please check with the latest version ?

**Comment by mlucchini** [comment]
Hi,
The clean build didn't solve the issue.
I'm targeting SDK 21 and building with the tools 21.1.2. AppCompat v7 21.0.3 but just tried with latest 22.1.0 and the same thing happens.
Is there a specific version I'd better use or try with?

**Comment by mlucchini** [comment]
I had removed the 'android:theme="@style/Theme.Mobihelp"' occurences in Mobihelp's AndroidManifest.xml in order to inherit from my app theme, but I guess some properties went missing then? It's fine if I keep your theme actually.

**Comment by tryprasannan** [comment]
When using a your own theme / custom theme with Mobihelp SDK, 
  1. Ensure the custom theme inherits from one of the variants of Theme.AppCompat
  2. The custom theme must also include the attributes from the equivalent Mobihelp theme. 
Eg. If the theme is light theme, include the attributes from the theme `Theme.MobihelpSDK.Light`  present in [res/values/themes.xml](https://github.com/freshdesk/mobihelp-android/blob/master/MobihelpSDK/res/values/themes.xml) in the custom theme. The icons are based on these attributes. 

If it still doesn't work, please let us know. Thanks.

**Comment by mlucchini** [comment]
I was extending Theme.AppCompat but missing the icons.
Cheers
