### ISSUE TITLE
Deep linking to solutions

### ISSUE THREAD

**Issue by myanimal** [freshdesk/mobihelp-android#15]
In the readme it states this functionality was introduced in 1.3.1. I can't find any documentation though. Is it possible to deep link to a specific solution?

**Comment by tryprasannan** [comment]
@myanimal Yes you can deep link to a specific solution in ticket replies. It works automatically on the SDK side. All you need to do is insert a link to the solution using "Insert Solution" option from within the reply box as usual.

**Comment by tryprasannan** [comment]
@myanimal We're marking this closed. If you still need more clarification feel free to re-open.

**Comment by myanimal** [comment]
Thanks @tryprasannan. Is there anyway to open a specific solution via an Intent or something like that? e.g.: pressing a button in the app shows a specific solution.

**Comment by hrishikesh-p** [comment]
There is no way to launch a particular article now. 

We are planning to add support for tags on solutions. This will allow you show articles containing a tag . for e.g  If your app has a billing section , you will able to add a help button that shows articles related to billing.  

This will be included in the next release . ( 3 weeks )
