### ISSUE TITLE
Changing the chat bubble icon color

### ISSUE THREAD

**Issue by tjerkw** [freshdesk/mobihelp-android#23]
We want to change the chat bubble icon.
The only way this can be done is hack into the code itself (change the image file).
Right?

**Comment by hrishikesh-p** [comment]
Yes, you are right . The way to achieve this currently would be to replace the 9patch images  include under resources. 

You can include the files with the same name "mobihelp_chat_bubble_agent.9.png"  under your app's resources  and the build should include your chat image.
