### ISSUE TITLE
Allow to pre populate text in description

### ISSUE THREAD

**Issue by MufriA** [freshdesk/mobihelp-android#7]
In some cases we know some text in description should be prepopulated, its better if can add some text before showing it to user.

**Comment by tryprasannan** [comment]
Can you please expand on the actual use case ? 
Is the text dynamic & is this something that the user necessarily needs to see ?
If the text is static, you can always pre-populate by adding it in the layout xml file.
If the text is static/dynamic, and user need not view the same, then it can be added as custom data.
Even if it is pre-populated, the user can remove it and just send their description of the issue.

**Comment by MufriA** [comment]
My app shows logos for services they use, say like Google logo, if an user uses unknown service which is not in our database they request to add it in database by providing the name of service.

As of now I pre populate this service name from the available accounts instead of requesting inputs from users, also users can remove / edit this by adding extra info like URL of the service.

Ofcourse I can use custom data in which case its not correct to send user info without user consent, if we display it in editable area user can remove / edit it if he is not comfortable.

**Comment by MufriA** [comment]
You can refer screenshots here - https://play.google.com/store/apps/details?id=com.mufri.authenticatorplus&hl=en

**Comment by tryprasannan** [comment]
Thanks for sharing the use case. We will consider adding support for this in a future release.

**Comment by tryprasannan** [comment]
@MufriA We've added support for pre-filling description when using the showFeedback API as of v1.5. For more information, please refer our [documentation](http://developer.freshdesk.com/mobihelp/android/api/reference/com/freshdesk/mobihelp/Mobihelp.html#showFeedback%28android.content.Context,%20com.freshdesk.mobihelp.FeedbackRequest%29).

**Comment by riyaz** [comment]
Cool, thanks for this.
